### ISSUE TITLE
Move to sbt org?

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-dynver#226]
@dwijnand would you be interested in moving this project to the sbt org, now that it has become such a de facto standard? especially since sbt/sbt-ci-release pulls in sbt-dynver, and sbt-ci-release is a de facto standard these days and has already moved from Olaf's personal account to the sbt org

it seems like a good idea to me for bus-factor / long-term maintenance reasons

**Comment by dwijnand** [comment]
Sure.  Done.

**Comment by SethTisue** [comment]
yay!
