### ISSUE TITLE
Admin stuff

### ISSUE THREAD

**Issue by SethTisue** [sbt/sbt-dynver#241]
@eed3si9n @dwijnand can I have admin rights (or maintainer rights or whatever) in this repo? I find myself wanting to do things like

• close or relocate issues
• add labels to issues
• enable the "Discussions" tab

also I might be able to help #239 go forward if a volunteer appears

**Comment by eed3si9n** [comment]
Closing this since it looks like you now have the admin rights.

**Comment by SethTisue** [comment]
thanks
