### ISSUE TITLE
-rcX Tag suffix ignored

### ISSUE THREAD

**Issue by caenrique** [sbt/sbt-dynver#280]
is there a way to force the plugin to use the exact tag for the version?

we have the convention of using `-rcX` for pre-release versions and this is not keeping that suffix. E.g. `v1.23.0-rc2` is being published as `v1.23.0`

**Comment by dwijnand** [comment]
See https://github.com/sbt/sbt-dynver#custom-version-string, you can use the `dynverGitDescribeOutput` to construct the version string.
