### ISSUE TITLE
Crossbuild to sbt 2.0.0 + Scala 3

### ISSUE THREAD

**Issue by BillyAutrey** [sbt/sbt-dynver#308]
sbt 2.0.0-M2 is available, so we can start cross-building this to 2.0 and add scala3 support.

**Comment by BillyAutrey** [comment]
https://github.com/sbt/sbt-dynver/pull/305 is in flight.

**Comment by eed3si9n** [comment]
#305 encountered a bunch of test errors, and as far as I know it's been stuck at that state. It would be good if someone wants to take a fresh stab at it to investigate the underlying cause(s).

**Comment by eed3si9n** [comment]
Fixed in https://github.com/sbt/sbt-dynver/pull/314
